<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon></ApplicationIcon>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpAgent.Core\SharpAgent.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\config.example.json" Link="config.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
