// <auto-generated />
// Source: https://models.dev/api.json
// Generator: scripts/generate-pi-builtin-providers.mjs

namespace Sharp.Core.Configuration;

internal static class BuiltInPiProviders
{
    public static IReadOnlyList<ProviderConfig> Create()
        => new List<ProviderConfig>
        {
            new ProviderConfig
            {
                Id = "openrouter",
                Api = ModelApiFormat.OpenAiCompletions,
                BaseUrl = "https://openrouter.ai/api/v1/",
                Models =
                [
                    new ModelConfig
                    {
                        Id = "openai/gpt-5.1-codex",
                        ContextWindow = 400000,
                        MaxOutputTokens = 128000
                    },
                ]
            },
            new ProviderConfig
            {
                Id = "xai",
                Api = ModelApiFormat.OpenAiCompletions,
                BaseUrl = "https://api.x.ai/v1/",
                Models =
                [
                    new ModelConfig
                    {
                        Id = "grok-4-fast-non-reasoning",
                        ContextWindow = 2000000,
                        MaxOutputTokens = 30000
                    },
                ]
            },
            new ProviderConfig
            {
                Id = "groq",
                Api = ModelApiFormat.OpenAiCompletions,
                BaseUrl = "https://api.groq.com/openai/v1/",
                Models =
                [
                    new ModelConfig
                    {
                        Id = "openai/gpt-oss-120b",
                        ContextWindow = 131072,
                        MaxOutputTokens = 65536
                    },
                ]
            },
            new ProviderConfig
            {
                Id = "cerebras",
                Api = ModelApiFormat.OpenAiCompletions,
                BaseUrl = "https://api.cerebras.ai/v1/",
                Models =
                [
                    new ModelConfig
                    {
                        Id = "zai-glm-4.7",
                        ContextWindow = 131072,
                        MaxOutputTokens = 40000
                    },
                ]
            },
            new ProviderConfig
            {
                Id = "zai",
                Api = ModelApiFormat.OpenAiCompletions,
                BaseUrl = "https://api.z.ai/api/coding/paas/v4/",
                Models =
                [
                    new ModelConfig
                    {
                        Id = "glm-4.6",
                        ContextWindow = 204800,
                        MaxOutputTokens = 131072
                    },
                ]
            },
            new ProviderConfig
            {
                Id = "mistral",
                Api = ModelApiFormat.OpenAiCompletions,
                BaseUrl = "https://api.mistral.ai/v1/",
                Models =
                [
                    new ModelConfig
                    {
                        Id = "devstral-medium-latest",
                        ContextWindow = 262144,
                        MaxOutputTokens = 262144
                    },
                ]
            },
            new ProviderConfig
            {
                Id = "minimax",
                Api = ModelApiFormat.AnthropicMessages,
                BaseUrl = "https://api.minimax.io/anthropic/v1/",
                Models =
                [
                    new ModelConfig
                    {
                        Id = "MiniMax-M2.1",
                        ContextWindow = 204800,
                        MaxOutputTokens = 131072
                    },
                ]
            },
            new ProviderConfig
            {
                Id = "minimax-cn",
                Api = ModelApiFormat.AnthropicMessages,
                BaseUrl = "https://api.minimaxi.com/anthropic/v1/",
                Models =
                [
                    new ModelConfig
                    {
                        Id = "MiniMax-M2.1",
                        ContextWindow = 204800,
                        MaxOutputTokens = 131072
                    },
                ]
            },
            new ProviderConfig
            {
                Id = "huggingface",
                Api = ModelApiFormat.OpenAiCompletions,
                BaseUrl = "https://router.huggingface.co/v1/",
                Models =
                [
                    new ModelConfig
                    {
                        Id = "moonshotai/Kimi-K2.5",
                        ContextWindow = 262144,
                        MaxOutputTokens = 262144
                    },
                ]
            },
            new ProviderConfig
            {
                Id = "opencode",
                Api = ModelApiFormat.AnthropicMessages,
                BaseUrl = "https://opencode.ai/zen/v1/",
                Models =
                [
                    new ModelConfig
                    {
                        Id = "claude-opus-4-6",
                        ContextWindow = 1000000,
                        MaxOutputTokens = 128000
                    },
                ]
            },
            new ProviderConfig
            {
                Id = "github-copilot",
                Api = ModelApiFormat.OpenAiCompletions,
                BaseUrl = "https://api.individual.githubcopilot.com/",
                Models =
                [
                    new ModelConfig
                    {
                        Id = "gpt-4o",
                        ContextWindow = 64000,
                        MaxOutputTokens = 16384
                    },
                ]
            },
            new ProviderConfig
            {
                Id = "kimi-coding",
                Api = ModelApiFormat.AnthropicMessages,
                BaseUrl = "https://api.kimi.com/coding/v1/",
                Models =
                [
                    new ModelConfig
                    {
                        Id = "kimi-k2-thinking",
                        ContextWindow = 262144,
                        MaxOutputTokens = 32768
                    },
                ]
            },
        };
}
