// <auto-generated />
// Source: https://models.dev/api.json
// Generator: scripts/generate-pi-builtin-providers.mjs

namespace Sharp.Core.Configuration;

internal static class BuiltInPiProviders
{
    public static IReadOnlyList<ProviderConfig> Create()
        => new List<ProviderConfig>
        {
            new ProviderConfig
            {
                Id = "openrouter",
                Api = ModelApiFormat.OpenAiCompletions,
                BaseUrl = "https://openrouter.ai/api/v1/",
                Models =
                [
                    new ModelConfig
                    {
                        Id = "openai/gpt-5.1-codex",
                        ContextWindow = 400000,
                        MaxOutputTokens = 128000
                    },
                ]
            },
            new ProviderConfig
            {
                Id = "xai",
                Api = ModelApiFormat.OpenAiCompletions,
                BaseUrl = "https://api.x.ai/v1/",
                Models =
                [
                    new ModelConfig
                    {
                        Id = "grok-4-fast-non-reasoning",
                        ContextWindow = 2000000,
                        MaxOutputTokens = 30000
                    },
                ]
            },
            new ProviderConfig
            {
                Id = "groq",
                Api = ModelApiFormat.OpenAiCompletions,
                BaseUrl = "https://api.groq.com/openai/v1/",
                Models =
                [
                    new ModelConfig
                    {
                        Id = "openai/gpt-oss-120b",
                        ContextWindow = 131072,
                        MaxOutputTokens = 65536
                    },
                ]
            },
            new ProviderConfig
            {
                Id = "cerebras",
                Api = ModelApiFormat.OpenAiCompletions,
                BaseUrl = "https://api.cerebras.ai/v1/",
                Models =
                [
                    new ModelConfig
                    {
                        Id = "zai-glm-4.7",
                        ContextWindow = 131072,
                        MaxOutputTokens = 40000
                    },
                ]
            },
            new ProviderConfig
            {
                Id = "zai",
                Api = ModelApiFormat.OpenAiCompletions,
                BaseUrl = "https://api.z.ai/api/coding/paas/v4/",
                Models =
                [
                    new ModelConfig
                    {
                        Id = "glm-4.6",
                        ContextWindow = 204800,
                        MaxOutputTokens = 131072
                    },
                ]
            },
            new ProviderConfig
            {
                Id = "mistral",
                Api = ModelApiFormat.OpenAiCompletions,
                BaseUrl = "https://api.mistral.ai/v1/",
                Models =
                [
                    new ModelConfig
                    {
                        Id = "devstral-medium-latest",
                        ContextWindow = 262144,
                        MaxOutputTokens = 262144
                    },
                ]
            },
            new ProviderConfig
            {
                Id = "minimax",
                Api = ModelApiFormat.AnthropicMessages,
                BaseUrl = "https://api.minimax.io/anthropic/v1/",
                Models =
                [
                    new ModelConfig
                    {
                        Id = "MiniMax-M2.1",
                        ContextWindow = 204800,
                        MaxOutputTokens = 131072
                    },
                ]
            },
            new ProviderConfig
            {
                Id = "minimax-cn",
                Api = ModelApiFormat.AnthropicMessages,
                BaseUrl = "https://api.minimaxi.com/anthropic/v1/",
                Models =
                [
                    new ModelConfig
                    {
                        Id = "MiniMax-M2.1",
                        ContextWindow = 204800,
                        MaxOutputTokens = 131072
                    },
                ]
            },
            new ProviderConfig
            {
                Id = "huggingface",
                Api = ModelApiFormat.OpenAiCompletions,
                BaseUrl = "https://router.huggingface.co/v1/",
                Models =
                [
                    new ModelConfig
                    {
                        Id = "moonshotai/Kimi-K2.5",
                        ContextWindow = 262144,
                        MaxOutputTokens = 262144
                    },
                ]
            },
            new ProviderConfig
            {
                Id = "opencode",
                Api = ModelApiFormat.AnthropicMessages,
                BaseUrl = "https://opencode.ai/zen/v1/",
                Models =
                [
                    new ModelConfig
                    {
                        Id = "claude-opus-4-6",
                        ContextWindow = 1000000,
                        MaxOutputTokens = 128000
                    },
                ]
            },
            new ProviderConfig
            {
                Id = "github-copilot",
                Api = ModelApiFormat.OpenAiCompletions,
                BaseUrl = "https://api.individual.githubcopilot.com/",
                Models =
                [
                    new ModelConfig
                    {
                        Id = "gpt-4o",
                        ContextWindow = 64000,
                        MaxOutputTokens = 16384
                    },
                ]
            },
            new ProviderConfig
            {
                Id = "kimi-coding",
                Api = ModelApiFormat.AnthropicMessages,
                BaseUrl = "https://api.kimi.com/coding/v1/",
                Models =
                [
                    new ModelConfig
                    {
                        Id = "kimi-k2-thinking",
                        ContextWindow = 262144,
                        MaxOutputTokens = 32768
                    },
                ]
            },
            new ProviderConfig
            {
                Id = "google-antigravity",
                Api = ModelApiFormat.GoogleGeminiCli,
                BaseUrl = "https://daily-cloudcode-pa.sandbox.googleapis.com/",
                Models =
                [
                    new ModelConfig
                    {
                        Id = "gemini-3-pro-high",
                        ContextWindow = 1048576,
                        MaxOutputTokens = 65535,
                        Capabilities = new ModelCapabilitiesConfig
                        {
                            SupportsReasoning = true,
                            SupportsImageInput = true,
                            SupportsToolCall = true
                        },
                        Pricing = new ModelPricingConfig
                        {
                            InputPerMillionTokens = 2m,
                            OutputPerMillionTokens = 12m,
                            CacheReadPerMillionTokens = 0.2m,
                            CacheWritePerMillionTokens = 2.375m
                        }
                    },
                    new ModelConfig
                    {
                        Id = "gemini-3-pro-low",
                        ContextWindow = 1048576,
                        MaxOutputTokens = 65535,
                        Capabilities = new ModelCapabilitiesConfig
                        {
                            SupportsReasoning = true,
                            SupportsImageInput = true,
                            SupportsToolCall = true
                        },
                        Pricing = new ModelPricingConfig
                        {
                            InputPerMillionTokens = 2m,
                            OutputPerMillionTokens = 12m,
                            CacheReadPerMillionTokens = 0.2m,
                            CacheWritePerMillionTokens = 2.375m
                        }
                    },
                    new ModelConfig
                    {
                        Id = "gemini-3-flash",
                        ContextWindow = 1048576,
                        MaxOutputTokens = 65535,
                        Capabilities = new ModelCapabilitiesConfig
                        {
                            SupportsReasoning = true,
                            SupportsImageInput = true,
                            SupportsToolCall = true
                        },
                        Pricing = new ModelPricingConfig
                        {
                            InputPerMillionTokens = 0.5m,
                            OutputPerMillionTokens = 3m,
                            CacheReadPerMillionTokens = 0.5m,
                            CacheWritePerMillionTokens = 0m
                        }
                    },
                    new ModelConfig
                    {
                        Id = "claude-sonnet-4-5",
                        ContextWindow = 200000,
                        MaxOutputTokens = 64000,
                        Capabilities = new ModelCapabilitiesConfig
                        {
                            SupportsReasoning = false,
                            SupportsImageInput = true,
                            SupportsToolCall = true
                        },
                        Pricing = new ModelPricingConfig
                        {
                            InputPerMillionTokens = 3m,
                            OutputPerMillionTokens = 15m,
                            CacheReadPerMillionTokens = 0.3m,
                            CacheWritePerMillionTokens = 3.75m
                        }
                    },
                    new ModelConfig
                    {
                        Id = "claude-sonnet-4-5-thinking",
                        ContextWindow = 200000,
                        MaxOutputTokens = 64000,
                        Capabilities = new ModelCapabilitiesConfig
                        {
                            SupportsReasoning = true,
                            SupportsImageInput = true,
                            SupportsToolCall = true
                        },
                        Pricing = new ModelPricingConfig
                        {
                            InputPerMillionTokens = 3m,
                            OutputPerMillionTokens = 15m,
                            CacheReadPerMillionTokens = 0.3m,
                            CacheWritePerMillionTokens = 3.75m
                        }
                    },
                    new ModelConfig
                    {
                        Id = "claude-opus-4-5-thinking",
                        ContextWindow = 200000,
                        MaxOutputTokens = 64000,
                        Capabilities = new ModelCapabilitiesConfig
                        {
                            SupportsReasoning = true,
                            SupportsImageInput = true,
                            SupportsToolCall = true
                        },
                        Pricing = new ModelPricingConfig
                        {
                            InputPerMillionTokens = 5m,
                            OutputPerMillionTokens = 25m,
                            CacheReadPerMillionTokens = 0.5m,
                            CacheWritePerMillionTokens = 6.25m
                        }
                    },
                    new ModelConfig
                    {
                        Id = "claude-opus-4-6-thinking",
                        ContextWindow = 200000,
                        MaxOutputTokens = 128000,
                        Capabilities = new ModelCapabilitiesConfig
                        {
                            SupportsReasoning = true,
                            SupportsImageInput = true,
                            SupportsToolCall = true
                        },
                        Pricing = new ModelPricingConfig
                        {
                            InputPerMillionTokens = 5m,
                            OutputPerMillionTokens = 25m,
                            CacheReadPerMillionTokens = 0.5m,
                            CacheWritePerMillionTokens = 6.25m
                        }
                    },
                    new ModelConfig
                    {
                        Id = "gpt-oss-120b-medium",
                        ContextWindow = 131072,
                        MaxOutputTokens = 32768,
                        Capabilities = new ModelCapabilitiesConfig
                        {
                            SupportsReasoning = false,
                            SupportsImageInput = false,
                            SupportsToolCall = true
                        },
                        Pricing = new ModelPricingConfig
                        {
                            InputPerMillionTokens = 0.09m,
                            OutputPerMillionTokens = 0.36m,
                            CacheReadPerMillionTokens = 0m,
                            CacheWritePerMillionTokens = 0m
                        }
                    },
                ]
            },
        };
}
